In [223]:
import pandas as pd

In [224]:
weather_data = pd.read_csv('csv/weather/clean_weather_data.csv')
pmrp_run_data = pd.read_csv('csv/run/pmrp_run_data.csv')

In [225]:
pmrp_run_data.head()

,name,distance,moving_time,elapsed_time,total_elevation_gain,type,start_date,start_date_local,timezone,utc_offset,...,start_latlng,end_latlng,average_speed,max_speed,elev_high,elev_low,pr_count,distance_miles,moving_time_minutes,moving_time_hours
0,PMRP : Sore Heel Loop,7090.5,2341,2365,210.0,Run,2023-07-12T20:20:42Z,2023-07-12T16:20:42Z,(GMT-05:00) America/New_York,-14400.0,...,"[37.64469179324806, -83.71427628211677]","[37.64480469748378, -83.71436378918588]",3.029,13.532,348.9,259.0,0,4.41,39.02,0.65
1,PMRP : Sore Heel Loop and Drive By Loop,8973.2,2836,2882,368.6,Run,2023-05-28T18:17:37Z,2023-05-28T14:17:37Z,(GMT-05:00) America/New_York,-14400.0,...,"[37.64462482184172, -83.71412750333548]","[37.64463094063103, -83.7141434289515]",3.164,16.328,349.9,259.0,0,5.58,47.27,0.79
2,PMRP : Lode Loop and Lode Hill,2615.8,843,849,96.5,Run,2023-05-12T19:53:27Z,2023-05-12T15:53:27Z,(GMT-05:00) America/New_York,-14400.0,...,"[37.64475432224572, -83.71380949392915]","[37.644639406353235, -83.71410939842463]",3.103,7.168,339.3,267.6,0,1.63,14.05,0.23
3,PMRP : Lode Loop and Flat Holler Loop,9653.3,3349,3385,453.1,Run,2023-05-05T18:39:29Z,2023-05-05T14:39:29Z,(GMT-05:00) America/New_York,-14400.0,...,"[37.64486974105239, -83.71435523964465]","[37.644784580916166, -83.7140276748687]",2.882,14.712,332.0,259.2,1,6.00,55.82,0.93
4,PMRP : Drive By Loop and Lode Loop,5774.7,1769,1827,131.6,Run,2023-04-28T18:23:12Z,2023-04-28T14:23:12Z,(GMT-05:00) America/New_York,-14400.0,...,"[37.644651057198644, -83.71401585638523]","[37.644623816013336, -83.7140057142824]",3.264,11.087,333.2,258.4,1,3.59,29.48,0.49

In [226]:
weather_data.head()

,DATE,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,FOG,THUNDER,HAIL,RIME,WIND
0,2022-01-01,1.91,0.0,0.0,63.0,46.0,57.0,0.0,1.0,0.0,0.0,0.0
1,2022-01-02,1.44,0.0,0.0,70.0,50.0,50.0,0.0,0.0,0.0,0.0,0.0
2,2022-01-03,0.05,0.0,0.0,50.0,26.0,27.0,0.0,0.0,0.0,0.0,0.0
3,2022-01-04,0.00,0.0,0.0,32.0,19.0,23.0,0.0,0.0,0.0,0.0,0.0
4,2022-01-05,0.00,0.0,0.0,45.0,23.0,42.0,0.0,0.0,0.0,0.0,0.0

In [227]:
date_column_weather = weather_data['DATE']
data_type_weather = date_column_weather.dtype
print('Weather Date dtype: ', data_type_weather)

date_column_run = pmrp_run_data['start_date']
data_type_run = date_column_run.dtype
print('Run Date dtype: ', data_type_run)

weather_data['DATE'] = pd.to_datetime(weather_data['DATE'])
pmrp_run_data['start_date'] = pd.to_datetime(pmrp_run_data['start_date'])

date_column_weather = weather_data['DATE']
data_type_weather = date_column_weather.dtype
print('Weather Date dtype: ', data_type_weather)

date_column_run = pmrp_run_data['start_date']
data_type_run = date_column_run.dtype
print('Run Date dtype: ', data_type_run)

Weather Date dtype:  object
Run Date dtype:  object
Weather Date dtype:  datetime64[ns]
Run Date dtype:  datetime64[ns, UTC]

In [228]:
date_list_run = run_data['start_date'].tolist()
date_list_weather = weather_data['DATE'].tolist()

In [229]:
date_list_run

['2023-07-12T20:20:42Z',
 '2023-05-28T18:17:37Z',
 '2023-05-12T19:53:27Z',
 '2023-05-05T18:39:29Z',
 '2023-04-28T18:23:12Z',
 '2023-04-13T18:21:31Z',
 '2023-03-30T19:33:49Z',
 '2023-03-25T17:59:19Z',
 '2023-03-11T17:52:25Z',
 '2023-03-04T22:32:43Z',
 '2023-03-02T21:14:21Z',
 '2023-02-27T20:26:12Z',
 '2023-02-26T19:55:35Z',
 '2023-02-24T20:26:50Z',
 '2023-02-23T19:33:36Z',
 '2023-01-23T22:24:52Z',
 '2023-01-23T21:54:18Z',
 '2022-10-26T16:43:13Z',
 '2022-10-13T16:37:12Z',
 '2022-10-12T15:25:40Z']

In [230]:
date_list_weather

[Timestamp('2022-01-01 00:00:00'),
 Timestamp('2022-01-02 00:00:00'),
 Timestamp('2022-01-03 00:00:00'),
 Timestamp('2022-01-04 00:00:00'),
 Timestamp('2022-01-05 00:00:00'),
 Timestamp('2022-01-06 00:00:00'),
 Timestamp('2022-01-07 00:00:00'),
 Timestamp('2022-01-08 00:00:00'),
 Timestamp('2022-01-09 00:00:00'),
 Timestamp('2022-01-10 00:00:00'),
 Timestamp('2022-01-11 00:00:00'),
 Timestamp('2022-01-12 00:00:00'),
 Timestamp('2022-01-13 00:00:00'),
 Timestamp('2022-01-14 00:00:00'),
 Timestamp('2022-01-15 00:00:00'),
 Timestamp('2022-01-16 00:00:00'),
 Timestamp('2022-01-17 00:00:00'),
 Timestamp('2022-01-18 00:00:00'),
 Timestamp('2022-01-19 00:00:00'),
 Timestamp('2022-01-20 00:00:00'),
 Timestamp('2022-01-21 00:00:00'),
 Timestamp('2022-01-22 00:00:00'),
 Timestamp('2022-01-23 00:00:00'),
 Timestamp('2022-01-24 00:00:00'),
 Timestamp('2022-01-25 00:00:00'),
 Timestamp('2022-01-26 00:00:00'),
 Timestamp('2022-01-27 00:00:00'),
 Timestamp('2022-01-28 00:00:00'),
 Timestamp('2022-01-29 00:00:00'),
 Timestamp('2022-01-30 00:00:00'),
 Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-02-01 00:00:00'),
 Timestamp('2022-02-02 00:00:00'),
 Timestamp('2022-02-03 00:00:00'),
 Timestamp('2022-02-04 00:00:00'),
 Timestamp('2022-02-05 00:00:00'),
 Timestamp('2022-02-06 00:00:00'),
 Timestamp('2022-02-07 00:00:00'),
 Timestamp('2022-02-08 00:00:00'),
 Timestamp('2022-02-09 00:00:00'),
 Timestamp('2022-02-10 00:00:00'),
 Timestamp('2022-02-11 00:00:00'),
 Timestamp('2022-02-12 00:00:00'),
 Timestamp('2022-02-13 00:00:00'),
 Timestamp('2022-02-14 00:00:00'),
 Timestamp('2022-02-15 00:00:00'),
 Timestamp('2022-02-16 00:00:00'),
 Timestamp('2022-02-17 00:00:00'),
 Timestamp('2022-02-18 00:00:00'),
 Timestamp('2022-02-19 00:00:00'),
 Timestamp('2022-02-20 00:00:00'),
 Timestamp('2022-02-21 00:00:00'),
 Timestamp('2022-02-22 00:00:00'),
 Timestamp('2022-02-23 00:00:00'),
 Timestamp('2022-02-24 00:00:00'),
 Timestamp('2022-02-25 00:00:00'),
 Timestamp('2022-02-26 00:00:00'),
 Timestamp('2022-02-27 00:00:00'),
 Timestamp('2022-02-28 00:00:00'),
 Timestamp('2022-03-01 00:00:00'),
 Timestamp('2022-03-02 00:00:00'),
 Timestamp('2022-03-03 00:00:00'),
 Timestamp('2022-03-04 00:00:00'),
 Timestamp('2022-03-05 00:00:00'),
 Timestamp('2022-03-06 00:00:00'),
 Timestamp('2022-03-07 00:00:00'),
 Timestamp('2022-03-08 00:00:00'),
 Timestamp('2022-03-09 00:00:00'),
 Timestamp('2022-03-10 00:00:00'),
 Timestamp('2022-03-11 00:00:00'),
 Timestamp('2022-03-12 00:00:00'),
 Timestamp('2022-03-13 00:00:00'),
 Timestamp('2022-03-14 00:00:00'),
 Timestamp('2022-03-15 00:00:00'),
 Timestamp('2022-03-16 00:00:00'),
 Timestamp('2022-03-17 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-19 00:00:00'),
 Timestamp('2022-03-20 00:00:00'),
 Timestamp('2022-03-21 00:00:00'),
 Timestamp('2022-03-22 00:00:00'),
 Timestamp('2022-03-23 00:00:00'),
 Timestamp('2022-03-24 00:00:00'),
 Timestamp('2022-03-25 00:00:00'),
 Timestamp('2022-03-26 00:00:00'),
 Timestamp('2022-03-27 00:00:00'),
 Timestamp('2022-03-28 00:00:00'),
 Timestamp('2022-03-29 00:00:00'),
 Timestamp('2022-03-30 00:00:00'),
 Timestamp('2022-03-31 00:00:00'),
 Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-04-02 00:00:00'),
 Timestamp('2022-04-03 00:00:00'),
 Timestamp('2022-04-04 00:00:00'),
 Timestamp('2022-04-05 00:00:00'),
 Timestamp('2022-04-06 00:00:00'),
 Timestamp('2022-04-07 00:00:00'),
 Timestamp('2022-04-08 00:00:00'),
 Timestamp('2022-04-09 00:00:00'),
 Timestamp('2022-04-10 00:00:00'),
 Timestamp('2022-04-11 00:00:00'),
 Timestamp('2022-04-12 00:00:00'),
 Timestamp('2022-04-13 00:00:00'),
 Timestamp('2022-04-14 00:00:00'),
 Timestamp('2022-04-15 00:00:00'),
 Timestamp('2022-04-16 00:00:00'),
 Timestamp('2022-04-17 00:00:00'),
 Timestamp('2022-04-18 00:00:00'),
 Timestamp('2022-04-20 00:00:00'),
 Timestamp('2022-04-21 00:00:00'),
 Timestamp('2022-04-22 00:00:00'),
 Timestamp('2022-04-23 00:00:00'),
 Timestamp('2022-04-24 00:00:00'),
 Timestamp('2022-04-25 00:00:00'),
 Timestamp('2022-04-26 00:00:00'),
 Timestamp('2022-04-27 00:00:00'),
 Timestamp('2022-04-28 00:00:00'),
 Timestamp('2022-04-29 00:00:00'),
 Timestamp('2022-04-30 00:00:00'),
 Timestamp('2022-05-01 00:00:00'),
 Timestamp('2022-05-02 00:00:00'),
 Timestamp('2022-05-03 00:00:00'),
 Timestamp('2022-05-04 00:00:00'),
 Timestamp('2022-05-05 00:00:00'),
 Timestamp('2022-05-06 00:00:00'),
 Timestamp('2022-05-07 00:00:00'),
 Timestamp('2022-05-08 00:00:00'),
 Timestamp('2022-05-09 00:00:00'),
 Timestamp('2022-05-10 00:00:00'),
 Timestamp('2022-05-11 00:00:00'),
 Timestamp('2022-05-12 00:00:00'),
 Timestamp('2022-05-13 00:00:00'),
 Timestamp('2022-05-14 00:00:00'),
 Timestamp('2022-05-15 00:00:00'),
 Timestamp('2022-05-16 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-18 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-20 00:00:00'),
 Timestamp('2022-05-21 00:00:00'),
 Timestamp('2022-05-22 00:00:00'),
 Timestamp('2022-05-23 00:00:00'),
 Timestamp('2022-05-24 00:00:00'),
 Timestamp('2022-05-25 00:00:00'),
 Timestamp('2022-05-26 00:00:00'),
 Timestamp('2022-05-27 00:00:00'),
 Timestamp('2022-05-28 00:00:00'),
 Timestamp('2022-05-29 00:00:00'),
 Timestamp('2022-05-30 00:00:00'),
 Timestamp('2022-05-31 00:00:00'),
 Timestamp('2022-06-01 00:00:00'),
 Timestamp('2022-06-02 00:00:00'),
 Timestamp('2022-06-03 00:00:00'),
 Timestamp('2022-06-04 00:00:00'),
 Timestamp('2022-06-05 00:00:00'),
 Timestamp('2022-06-06 00:00:00'),
 Timestamp('2022-06-07 00:00:00'),
 Timestamp('2022-06-08 00:00:00'),
 Timestamp('2022-06-09 00:00:00'),
 Timestamp('2022-06-10 00:00:00'),
 Timestamp('2022-06-11 00:00:00'),
 Timestamp('2022-06-12 00:00:00'),
 Timestamp('2022-06-13 00:00:00'),
 Timestamp('2022-06-14 00:00:00'),
 Timestamp('2022-06-15 00:00:00'),
 Timestamp('2022-06-16 00:00:00'),
 Timestamp('2022-06-17 00:00:00'),
 Timestamp('2022-06-18 00:00:00'),
 Timestamp('2022-06-19 00:00:00'),
 Timestamp('2022-06-20 00:00:00'),
 Timestamp('2022-06-21 00:00:00'),
 Timestamp('2022-06-22 00:00:00'),
 Timestamp('2022-06-23 00:00:00'),
 Timestamp('2022-06-24 00:00:00'),
 Timestamp('2022-06-25 00:00:00'),
 Timestamp('2022-06-26 00:00:00'),
 Timestamp('2022-06-27 00:00:00'),
 Timestamp('2022-06-28 00:00:00'),
 Timestamp('2022-06-29 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-07-01 00:00:00'),
 Timestamp('2022-07-02 00:00:00'),
 Timestamp('2022-07-03 00:00:00'),
 Timestamp('2022-07-04 00:00:00'),
 Timestamp('2022-07-05 00:00:00'),
 Timestamp('2022-07-06 00:00:00'),
 Timestamp('2022-07-07 00:00:00'),
 Timestamp('2022-07-08 00:00:00'),
 Timestamp('2022-07-09 00:00:00'),
 Timestamp('2022-07-10 00:00:00'),
 Timestamp('2022-07-11 00:00:00'),
 Timestamp('2022-07-12 00:00:00'),
 Timestamp('2022-07-13 00:00:00'),
 Timestamp('2022-07-14 00:00:00'),
 Timestamp('2022-07-15 00:00:00'),
 Timestamp('2022-07-16 00:00:00'),
 Timestamp('2022-07-17 00:00:00'),
 Timestamp('2022-07-18 00:00:00'),
 Timestamp('2022-07-19 00:00:00'),
 Timestamp('2022-07-20 00:00:00'),
 Timestamp('2022-07-21 00:00:00'),
 Timestamp('2022-07-22 00:00:00'),
 Timestamp('2022-07-23 00:00:00'),
 Timestamp('2022-07-24 00:00:00'),
 Timestamp('2022-07-25 00:00:00'),
 Timestamp('2022-07-26 00:00:00'),
 Timestamp('2022-07-27 00:00:00'),
 Timestamp('2022-07-28 00:00:00'),
 Timestamp('2022-07-29 00:00:00'),
 Timestamp('2022-07-30 00:00:00'),
 Timestamp('2022-07-31 00:00:00'),
 Timestamp('2022-08-01 00:00:00'),
 Timestamp('2022-08-03 00:00:00'),
 Timestamp('2022-08-04 00:00:00'),
 Timestamp('2022-08-05 00:00:00'),
 Timestamp('2022-08-06 00:00:00'),
 Timestamp('2022-08-07 00:00:00'),
 Timestamp('2022-08-08 00:00:00'),
 Timestamp('2022-08-09 00:00:00'),
 Timestamp('2022-08-10 00:00:00'),
 Timestamp('2022-08-11 00:00:00'),
 Timestamp('2022-08-12 00:00:00'),
 Timestamp('2022-08-13 00:00:00'),
 Timestamp('2022-08-14 00:00:00'),
 Timestamp('2022-08-15 00:00:00'),
 Timestamp('2022-08-16 00:00:00'),
 Timestamp('2022-08-17 00:00:00'),
 Timestamp('2022-08-18 00:00:00'),
 Timestamp('2022-08-19 00:00:00'),
 Timestamp('2022-08-20 00:00:00'),
 Timestamp('2022-08-21 00:00:00'),
 Timestamp('2022-08-22 00:00:00'),
 Timestamp('2022-08-23 00:00:00'),
 Timestamp('2022-08-24 00:00:00'),
 Timestamp('2022-08-25 00:00:00'),
 Timestamp('2022-08-26 00:00:00'),
 Timestamp('2022-08-27 00:00:00'),
 Timestamp('2022-08-28 00:00:00'),
 Timestamp('2022-08-29 00:00:00'),
 Timestamp('2022-08-30 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-09-01 00:00:00'),
 Timestamp('2022-09-02 00:00:00'),
 Timestamp('2022-09-03 00:00:00'),
 Timestamp('2022-09-04 00:00:00'),
 Timestamp('2022-09-05 00:00:00'),
 Timestamp('2022-09-06 00:00:00'),
 Timestamp('2022-09-07 00:00:00'),
 Timestamp('2022-09-08 00:00:00'),
 Timestamp('2022-09-09 00:00:00'),
 Timestamp('2022-09-10 00:00:00'),
 Timestamp('2022-09-11 00:00:00'),
 Timestamp('2022-09-12 00:00:00'),
 Timestamp('2022-09-13 00:00:00'),
 Timestamp('2022-09-14 00:00:00'),
 Timestamp('2022-09-15 00:00:00'),
 Timestamp('2022-09-16 00:00:00'),
 Timestamp('2022-09-17 00:00:00'),
 Timestamp('2022-09-18 00:00:00'),
 Timestamp('2022-09-19 00:00:00'),
 Timestamp('2022-09-20 00:00:00'),
 Timestamp('2022-09-21 00:00:00'),
 Timestamp('2022-09-22 00:00:00'),
 Timestamp('2022-09-23 00:00:00'),
 Timestamp('2022-09-24 00:00:00'),
 Timestamp('2022-09-25 00:00:00'),
 Timestamp('2022-09-26 00:00:00'),
 Timestamp('2022-09-27 00:00:00'),
 Timestamp('2022-09-28 00:00:00'),
 Timestamp('2022-09-29 00:00:00'),
 Timestamp('2022-09-30 00:00:00'),
 Timestamp('2022-10-01 00:00:00'),
 Timestamp('2022-10-02 00:00:00'),
 Timestamp('2022-10-03 00:00:00'),
 Timestamp('2022-10-04 00:00:00'),
 Timestamp('2022-10-05 00:00:00'),
 Timestamp('2022-10-06 00:00:00'),
 Timestamp('2022-10-07 00:00:00'),
 Timestamp('2022-10-08 00:00:00'),
 Timestamp('2022-10-09 00:00:00'),
 Timestamp('2022-10-10 00:00:00'),
 Timestamp('2022-10-11 00:00:00'),
 Timestamp('2022-10-12 00:00:00'),
 Timestamp('2022-10-13 00:00:00'),
 Timestamp('2022-10-14 00:00:00'),
 Timestamp('2022-10-15 00:00:00'),
 Timestamp('2022-10-16 00:00:00'),
 Timestamp('2022-10-17 00:00:00'),
 Timestamp('2022-10-18 00:00:00'),
 Timestamp('2022-10-19 00:00:00'),
 Timestamp('2022-10-20 00:00:00'),
 Timestamp('2022-10-21 00:00:00'),
 Timestamp('2022-10-22 00:00:00'),
 Timestamp('2022-10-23 00:00:00'),
 Timestamp('2022-10-24 00:00:00'),
 Timestamp('2022-10-25 00:00:00'),
 Timestamp('2022-10-26 00:00:00'),
 Timestamp('2022-10-27 00:00:00'),
 Timestamp('2022-10-28 00:00:00'),
 Timestamp('2022-10-29 00:00:00'),
 Timestamp('2022-10-30 00:00:00'),
 Timestamp('2022-10-31 00:00:00'),
 Timestamp('2022-11-01 00:00:00'),
 Timestamp('2022-11-02 00:00:00'),
 Timestamp('2022-11-03 00:00:00'),
 Timestamp('2022-11-04 00:00:00'),
 Timestamp('2022-11-05 00:00:00'),
 Timestamp('2022-11-06 00:00:00'),
 Timestamp('2022-11-07 00:00:00'),
 Timestamp('2022-11-08 00:00:00'),
 Timestamp('2022-11-09 00:00:00'),
 Timestamp('2022-11-10 00:00:00'),
 Timestamp('2022-11-11 00:00:00'),
 Timestamp('2022-11-12 00:00:00'),
 Timestamp('2022-11-13 00:00:00'),
 Timestamp('2022-11-14 00:00:00'),
 Timestamp('2022-11-15 00:00:00'),
 Timestamp('2022-11-16 00:00:00'),
 Timestamp('2022-11-17 00:00:00'),
 Timestamp('2022-11-18 00:00:00'),
 Timestamp('2022-11-19 00:00:00'),
 Timestamp('2022-11-20 00:00:00'),
 Timestamp('2022-11-21 00:00:00'),
 Timestamp('2022-11-22 00:00:00'),
 Timestamp('2022-11-23 00:00:00'),
 Timestamp('2022-11-24 00:00:00'),
 Timestamp('2022-11-25 00:00:00'),
 Timestamp('2022-11-26 00:00:00'),
 Timestamp('2022-11-27 00:00:00'),
 Timestamp('2022-11-28 00:00:00'),
 Timestamp('2022-11-29 00:00:00'),
 Timestamp('2022-11-30 00:00:00'),
 Timestamp('2022-12-01 00:00:00'),
 Timestamp('2022-12-02 00:00:00'),
 Timestamp('2022-12-03 00:00:00'),
 Timestamp('2022-12-04 00:00:00'),
 Timestamp('2022-12-05 00:00:00'),
 Timestamp('2022-12-06 00:00:00'),
 Timestamp('2022-12-07 00:00:00'),
 Timestamp('2022-12-08 00:00:00'),
 Timestamp('2022-12-09 00:00:00'),
 Timestamp('2022-12-10 00:00:00'),
 Timestamp('2022-12-11 00:00:00'),
 Timestamp('2022-12-12 00:00:00'),
 Timestamp('2022-12-13 00:00:00'),
 Timestamp('2022-12-14 00:00:00'),
 Timestamp('2022-12-15 00:00:00'),
 Timestamp('2022-12-16 00:00:00'),
 Timestamp('2022-12-17 00:00:00'),
 Timestamp('2022-12-18 00:00:00'),
 Timestamp('2022-12-19 00:00:00'),
 Timestamp('2022-12-20 00:00:00'),
 Timestamp('2022-12-21 00:00:00'),
 Timestamp('2022-12-22 00:00:00'),
 Timestamp('2022-12-23 00:00:00'),
 Timestamp('2022-12-24 00:00:00'),
 Timestamp('2022-12-25 00:00:00'),
 Timestamp('2022-12-26 00:00:00'),
 Timestamp('2022-12-27 00:00:00'),
 Timestamp('2022-12-28 00:00:00'),
 Timestamp('2022-12-29 00:00:00'),
 Timestamp('2022-12-30 00:00:00'),
 Timestamp('2022-12-31 00:00:00'),
 Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-01-02 00:00:00'),
 Timestamp('2023-01-03 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-01-06 00:00:00'),
 Timestamp('2023-01-07 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-01-10 00:00:00'),
 Timestamp('2023-01-11 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-01-13 00:00:00'),
 Timestamp('2023-01-14 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-01-16 00:00:00'),
 Timestamp('2023-01-17 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-01-19 00:00:00'),
 Timestamp('2023-01-20 00:00:00'),
 Timestamp('2023-01-21 00:00:00'),
 Timestamp('2023-01-22 00:00:00'),
 Timestamp('2023-01-23 00:00:00'),
 Timestamp('2023-01-24 00:00:00'),
 Timestamp('2023-01-25 00:00:00'),
 Timestamp('2023-01-26 00:00:00'),
 Timestamp('2023-01-27 00:00:00'),
 Timestamp('2023-01-28 00:00:00'),
 Timestamp('2023-01-29 00:00:00'),
 Timestamp('2023-01-30 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-02-01 00:00:00'),
 Timestamp('2023-02-02 00:00:00'),
 Timestamp('2023-02-03 00:00:00'),
 Timestamp('2023-02-04 00:00:00'),
 Timestamp('2023-02-05 00:00:00'),
 Timestamp('2023-02-06 00:00:00'),
 Timestamp('2023-02-07 00:00:00'),
 Timestamp('2023-02-08 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-02-10 00:00:00'),
 Timestamp('2023-02-11 00:00:00'),
 Timestamp('2023-02-12 00:00:00'),
 Timestamp('2023-02-13 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-02-16 00:00:00'),
 Timestamp('2023-02-17 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-02-19 00:00:00'),
 Timestamp('2023-02-20 00:00:00'),
 Timestamp('2023-02-21 00:00:00'),
 Timestamp('2023-02-22 00:00:00'),
 Timestamp('2023-02-23 00:00:00'),
 Timestamp('2023-02-24 00:00:00'),
 Timestamp('2023-02-25 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-02-28 00:00:00'),
 Timestamp('2023-03-01 00:00:00'),
 Timestamp('2023-03-02 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-04 00:00:00'),
 Timestamp('2023-03-05 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-03-07 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-03-10 00:00:00'),
 Timestamp('2023-03-11 00:00:00'),
 Timestamp('2023-03-12 00:00:00'),
 Timestamp('2023-03-13 00:00:00'),
 Timestamp('2023-03-14 00:00:00'),
 Timestamp('2023-03-15 00:00:00'),
 Timestamp('2023-03-16 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-03-18 00:00:00'),
 Timestamp('2023-03-19 00:00:00'),
 Timestamp('2023-03-20 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-03-22 00:00:00'),
 Timestamp('2023-03-23 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-03-25 00:00:00'),
 Timestamp('2023-03-26 00:00:00'),
 Timestamp('2023-03-27 00:00:00'),
 Timestamp('2023-03-28 00:00:00'),
 Timestamp('2023-03-29 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-04-03 00:00:00'),
 Timestamp('2023-04-04 00:00:00'),
 Timestamp('2023-04-05 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-04-08 00:00:00'),
 Timestamp('2023-04-09 00:00:00'),
 Timestamp('2023-04-10 00:00:00'),
 Timestamp('2023-04-11 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-04-13 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-04-15 00:00:00'),
 Timestamp('2023-04-16 00:00:00'),
 Timestamp('2023-04-17 00:00:00'),
 Timestamp('2023-04-18 00:00:00'),
 Timestamp('2023-04-19 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-04-21 00:00:00'),
 Timestamp('2023-04-22 00:00:00'),
 Timestamp('2023-04-23 00:00:00'),
 Timestamp('2023-04-24 00:00:00'),
 Timestamp('2023-04-25 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-04-27 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-04-30 00:00:00'),
 Timestamp('2023-05-01 00:00:00'),
 Timestamp('2023-05-02 00:00:00'),
 Timestamp('2023-05-03 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-05-06 00:00:00'),
 Timestamp('2023-05-07 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-05-09 00:00:00'),
 Timestamp('2023-05-10 00:00:00'),
 Timestamp('2023-05-11 00:00:00'),
 Timestamp('2023-05-12 00:00:00'),
 Timestamp('2023-05-13 00:00:00'),
 Timestamp('2023-05-14 00:00:00'),
 Timestamp('2023-05-15 00:00:00'),
 Timestamp('2023-05-16 00:00:00'),
 Timestamp('2023-05-17 00:00:00'),
 Timestamp('2023-05-18 00:00:00'),
 Timestamp('2023-05-19 00:00:00'),
 Timestamp('2023-05-20 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-05-22 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-05-24 00:00:00'),
 Timestamp('2023-05-25 00:00:00'),
 Timestamp('2023-05-26 00:00:00'),
 Timestamp('2023-05-27 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-05-29 00:00:00'),
 Timestamp('2023-05-30 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-06-01 00:00:00'),
 Timestamp('2023-06-02 00:00:00'),
 Timestamp('2023-06-03 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-06-06 00:00:00'),
 Timestamp('2023-06-07 00:00:00'),
 Timestamp('2023-06-08 00:00:00'),
 Timestamp('2023-06-09 00:00:00'),
 Timestamp('2023-06-10 00:00:00'),
 Timestamp('2023-06-11 00:00:00'),
 Timestamp('2023-06-12 00:00:00'),
 Timestamp('2023-06-13 00:00:00'),
 Timestamp('2023-06-14 00:00:00'),
 Timestamp('2023-06-15 00:00:00'),
 Timestamp('2023-06-16 00:00:00'),
 Timestamp('2023-06-17 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-06-19 00:00:00'),
 Timestamp('2023-06-20 00:00:00'),
 Timestamp('2023-06-21 00:00:00'),
 Timestamp('2023-06-22 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-06-25 00:00:00'),
 Timestamp('2023-06-26 00:00:00'),
 Timestamp('2023-06-27 00:00:00'),
 Timestamp('2023-06-28 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-06-30 00:00:00'),
 Timestamp('2023-07-01 00:00:00'),
 Timestamp('2023-07-02 00:00:00')]